### ISSUE TITLE
NEI requires JEI

### ISSUE THREAD

**Issue by Cloudninjakip** [TheCBProject/Feedback#16]
When i tried to use not enough items for 1.11.2 it said i needed just enough items to run it. This shouldn't be happening. Also I know that there is no 1.11.2 version but 1.11 mods work fine in 1.11.2

**Comment by covers1624** [comment]
Nei needs jei yes, this is so I dont get hundreds of reports saying Nei is broken because it's not displaying recipes from x mod.
