### ISSUE TITLE
[FMP] Microblock render crash 1.10.2

### ISSUE THREAD

**Issue by Daihok41** [TheCBProject/Feedback#17]
Several mods are involved but mezz said to post here.
Here is the crash report. Seems to be a microblock problem but not sure.

https://pastebin.com/L9yHkZvt

**Comment by covers1624** [comment]
The only way this can happen is if a pipeline operation is null and that really isnt possible..
Was this a one time crash or is there a consistent way to reproduce it?

**Comment by Daihok41** [comment]
I can reproduce this everytime. Yea hope this one gets fixed otherwise i gotta remove project red which needed this lol.

**Comment by covers1624** [comment]
Can you cull down the mod list to the minimum mods required to reproduce this please?

**Comment by Daihok41** [comment]
Sure ill try.

**Comment by Daihok41** [comment]
Here this is with only 22 mods vs 162
https://pastebin.com/fmBVp4fx

**Comment by covers1624** [comment]
Thanks! ill get that tested today hopefully.

**Comment by Daihok41** [comment]
Awesome! Yea this would be a good one to get fixed lol. Its wierd though can only produce the crash doin certain things I been trying to find all the ways i could reproduce but have only found 2 ways so far that i can constantly reproduce the crash.

**Comment by Daihok41** [comment]
Got any progress on this? Was just curious was really wanting to start my world up this weekend but eh i can wait dont really want to remove project red lol.

**Comment by MrTJP** [comment]
Try with JUST fmp. Then, if it works, add the Project Red mods. If it still works, continue adding until you find the one that causes this. Like @covers1624 said, this shouldn't be happening, and it isn't for most other people.

**Comment by Daihok41** [comment]
k Ill try and lower the mods even more see what happens had it down to just 22 in the pack and still was happening but we will see. I actually have a feeling that it may be gendustry thats the problem gonna try with just FMP jei and gendustry see what happens.

**Comment by Daihok41** [comment]
I think its most definately Gendustry causeing it. Just tryed with only 6 mods installed and crashed, gonne try without Gendustry just not sure if i can reproduce without.

**Comment by Daihok41** [comment]
Nope still Reproduced the crash with only 3 mods installed Here is the report.

https://pastebin.com/9pkLxvL2

This is just with JEI, CCLIB, and FMP, I have found 2 ways to get it to crash, Just scrolling through the item pages in JEI or type @g in jei both cause to crash. And sorry for all the posts just trying to help as much as i can. I dont know anything about coding so im not much help there all i can really do is just try and find different ways to reproduce the crash. Yea if anyone else could test it with these 3 mods just so i know its not just me would be great.

**Comment by Daihok41** [comment]
Well after all this fuss I really feel like a dope I found what the problem is. Something in my texture pack causeing it. I removed the texture pack it works fine. Now i feel like dope for all the fuss. I just dont know what in the texture pack is causing it. Never would have thought a texture pack would even cause it. So it never occured to me to remove the texture pack and check it.

**Comment by Daihok41** [comment]
I have narrowed down the textures whats causing it, Is there anyway for me to remove the microblocks for the 2 textures thats causing the crash?

**Comment by covers1624** [comment]
Ah, was thinking that, we need to make the system a tiny bit more robust, I have some ideas bit they need to bake a little bit. Gonna call this a bug as texture resolution for quads is retuning null textures and somehow messing up the transforms fmp builds.

**Comment by Daihok41** [comment]
Yea i found the 2 textures causeing it, Was the Oak bookshelf, and the Red stained Glass/pane

**Comment by covers1624** [comment]
1.10 this is going to be almost impossible to fix without a breaking change to how rendering is done in parts. 1.11 part rendering is going to be rewritten so this issue will be caught with the shotgun approach.

**Comment by Flexico** [comment]
Has anyone found a workaround for this, to at least not render stuff that would crash? Because I'm just not able to search certain things in JEI now.

**Comment by covers1624** [comment]
I guess you could use CraftTweaker to hide the items in JEI, sadly there is no work around.
