### ISSUE TITLE
CodeChicken Lib 1.11.2-2.6.0.254 crash the server at startup

### ISSUE THREAD

**Issue by Insane96** [TheCBProject/Feedback#18]
CodeChicken Lib 1.11.2-2.6.0.254-universal
Just with CodechickenLib installed
FML Log: https://pastebin.com/GDTxXw8s
Crash Log: https://pastebin.com/hvUgf0TB

Seems like that ccl tries to use Client side code

**Comment by covers1624** [comment]
Works fine for me, did this ever occur again?

**Comment by covers1624** [comment]
Fixed in latest 1.11 builds.
