### ISSUE TITLE
[WR-CBE] Nullpointer in WREventHandler: RedstoneEtherAddons.client()

### ISSUE THREAD

**Issue by Robijnvogel** [TheCBProject/Feedback#20]
See [this MC Forum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods?comment=24351)
NPE [at this line](https://github.com/TheCBProject/WirelessRedstone/blob/1.10.2/src/main/java/codechicken/wirelessredstone/handler/WREventHandler.java#L139).

It seems like _RedstoneEtherAddons#client_ can return null, so I'd advice either checking _clientManager_ for null in that query or in the _WREventHandler#clientTick_ method and if client is null, running RedstoneEtherAddons#loadClientManager before trying to "tick" the clientManager.

This is a Minecraft 1.10.2 issue, but it may exist in MC 1.11+ as well.

**Comment by covers1624** [comment]
Hmm, im not sure why this could ever occur.. I shall look in to it.

**Comment by victoroos** [comment]
Yeah, I'm the guy. It probably has something to do with compatibility cause it started after I added a few mods. Vkr vic

**Comment by Robijnvogel** [comment]
Which mods?

**Comment by victoroos** [comment]
Not sure, I tried debugging with all my mods but can't seem to find the culprit.
:S sorry.

**Comment by covers1624** [comment]
This should basically never happen, Fixed for 1.11's release.

**Comment by Robijnvogel** [comment]
Commit reference?

**Comment by covers1624** [comment]
WirelessRedstone for 1.11 hasn't been released yet as FMP is undergoing changes, that being said, i haven't pushed a commit.

**Comment by victoroos** [comment]
Would it be possible it push it to the 1.10.2 for now? Seeing as 1.11 will take a long time to catch up :)

**Comment by Robijnvogel** [comment]
Also, it seems like this issue is still prevalent in the currently released build of WR. See [here](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1279956-chickenbones-mods?comment=24486).

I mean, it is an NPE on the same field at a different moment.

The actual problem here, is that RedstoneEther#clientEther isn't initialised on time in some rare cases. How could this initialisation be assured?
