### ISSUE TITLE
[1.10.2] [WR:CBE] NPE on world unload causing ID mapping to fail

### ISSUE THREAD

**Issue by linuxdaemon** [TheCBProject/Feedback#22]
During server shutdown, it appears WR-CBE is throwing a NullPointerException. I have been attempting to figure out why blocks were being replaced/removed over restarts (as in all instances of a block) and tracked it down to failed ID mapping during shutdown which appears to be caused by WR-CBE.

### Logs
- [fml-server log](https://gist.github.com/linuxdaemon/60e1b20c2108585065a4076562c70543)
- [Relevant stacktrace](https://gist.github.com/linuxdaemon/21057e420af1b0ce5396e6c1eb1a90cc)

### Versions
- Minecraft 1.10.2
- Forge 12.18.3.2316
- CCCore 1.10.2-2.4.1.102
- CCLib 1.10.2-2.5.9.283
- WR-CBE 1.10.2-2.0.0.18

**Comment by covers1624** [comment]
1.10 is no longer supported, 1.11 builds will be released soon.
