### ISSUE TITLE
MC Forums thread info [STILL] outdated

### ISSUE THREAD

**Issue by Robijnvogel** [TheCBProject/Feedback#24]
It has been ten months since I reported this: https://github.com/TheCBProject/NotEnoughItems/issues/67
@covers1624 , you said that you contacted Chickenbones and that he promised to update the thread.

In ten months nothing has actually changed, however the same set of questions keeps on coming, which eventually has led me to reporting the thread and requesting the forum admins to update the OP with up-to-date information.

This is the most important information, I think the OP is lacking:
- Stable **downloads** for these mods can be found [here](https://minecraft.curseforge.com/members/chicken_bones/projects). (Possibly) unstable downloads can be found [here](http://chickenbones.net/Pages/links.html).
- The [1.8+ versions of Not Enough Items](https://minecraft.curseforge.com/projects/not-enough-items-1-8) are reduced to an add-on to the [Just Enough Items mod](https://minecraft.curseforge.com/projects/just-enough-items-jei) and, as such, **require** the "**JEI**" version for that Minecraft version to be installed.
- After Minecraft version 1.8, Covers and TheCBProject took over development of ChickenBones' mods. As such, issues should be reported at [their Github](https://github.com/TheCBProject/Feedback).
- After Minecraft version 1.8.9, ChickenBones' Dependency preloader was deprecated. CodeChickenLib remains a required dependency for all of Chickenbones' mods, but now has to be downloaded manually.
- After Minecraft version 1.10.2, CodeChickenCore was merged into CodeChickenLib and therefore is no longer a dependency for any of his mods.

Of course, even if I lose it, the MC Forum admins remain calm. As such, they refuse to update the OP of the thread without at least telling ChickenBones (as the thread author) himself. And since they can't contact him on the forums, because he is no longer active there, I wonder in what way they could contact him.

@covers1624 what would be the best way to solve this issue and prevent it from happening again and again?

**Comment by Robijnvogel** [comment]
If this issue has not been responded to at December 9th, the mentioned additional information will be added to the OP of ChickenBones' thread by the forum moderators.

FYI. :)

**Comment by Robijnvogel** [comment]
The forum's OP should be edited somewhere in the near future now. If you have any questions, please contact an MC Forums admin. Preferrably CitricSquid.

**Comment by covers1624** [comment]
Huh, completely missed this, cb just got back from Japan, either way I'll have cb take a look at the edit that the admins have done, assuming he can still edit it that is, add any additional information.

**Comment by covers1624** [comment]
Also, the feedback tracker here was a failed experiment and will be removed in the future, the admins should NOT link here.

**Comment by Robijnvogel** [comment]
Okay
@covers1624 ChickenBones will have to link his MC Forum account to a/his Twitch account in order to log in. Just FYI.

**Comment by covers1624** [comment]
Yeah discovered that one myself..

**Comment by Chicken-Bones** [comment]
Updated, definitely willing to take suggestions on layout/missing content.
I tried to put the old post in a spoiler tag but it was remarkably uncooperative

**Comment by Robijnvogel** [comment]
I was still discussing this "list of missing information" with Kye_Duo and  ReiDaTecnologia and Kye_Duo reminded us that there was one I failed to address myself initially.


Namely:
The many questions and "issue reports" people asked about the world-specific and global settings. Especially concerning changing from recipe- to cheat-mode. What you say in your EAQ section, "_Q. I can't spawn items! A. Change from Recipe Mode to Cheat Mode_" does not seem to be sufficient.

Regarding to this, Kye_Duo wrote the following small guide:
"For those who are having trouble with the inventory, or any, options that don't want to work despite cycling through them try the following:
left click on the global button in the top right of the NEI options menu
look at the new button next to the options that aren't working, if any of them are active, right click on them to disable the global override.
The most common instance of this happening is the NEI inventory menu mod option has this activated on new worlds. Most commonly happens in 1.7.10."
If it isn't already, it would be great if this could be included in the OP.

Since the question isn't asked that often anymore, I don't think its "more detailed answer" definitely has to be included in the OP, but if it's not too much to ask, I would like you to. :)


Also, I am really happy to hear that you are back in one piece.
I will ask Kye_Duo and ReiDaTecnologia to go over the new layout of the OP as well. Actually... I will add you to the conversation on the MC forums, so you can read everything first-hand if you want to.
