### ISSUE TITLE
Crash when pressed "U" over invar ingot & cobblestone

### ISSUE THREAD

**Issue by SlyyJacob** [TheCBProject/Feedback#27]
My client crashes whenever I press "U" (show recipe in JEI) over invar ingot (or cobblestone, and surely others too, so far encountered these two).
In the log it mentions this item being the cause: net.minecraft.item.ItemBlock@3af7fe01
No idea what mod that comes from, no idea how to find out either, sorry.
Log: https://gist.github.com/SlyJacobTheBeast/bb99e500685d45dae88f9f39002fe8f7

Issue was posted in JEI github but I was redirected here.

**Comment by covers1624** [comment]
There is nothing that could cause this on my end. Someone's model implementation is broken, there is nothing i can do about it.
