### ISSUE TITLE
ForgeMultipart issue with covers and GTCE

### ISSUE THREAD

**Issue by ShaCraft** [TheCBProject/Feedback#28]
sorry I not sure what tracker I should have used. so this is a copy of issue 44 on ForgeMultipart.
https://github.com/TheCBProject/ForgeMultipart/issues/44

Using any 1.12.2 versoin of Forge with any FMP version results in this crash.
Trying to place a cover on a gtce wire (it crashes as soon as you point a cover at a wire):
Bad invokespecial instruction: current class isn't assignable to reference class.
https://pastebin.com/k12DG5pv

With all up to date mods on Forge 2758
https://pastebin.com/CU97narx

**Comment by covers1624** [comment]
Im phasing out this tracker, was a nice idea but not really too useful, I just havent had time to look into that specific issue yet.
