### ISSUE TITLE
LAN hosting dropping players

### ISSUE THREAD

**Issue by Sudomeapizza** [TheCBProject/Feedback#30]
Mods directly talking about: EnderStorage 2.4.6.137. Ender IO 5.1.51, EnderCore 1.12.2-0.5.68
Mod List: [https://pastebin.com/uACw2h5p](https://pastebin.com/uACw2h5p)
Full Log: [https://pastebin.com/4kRYUzR9](https://pastebin.com/4kRYUzR9)
Crash Log: is none (tldr, kicks from server but not single player)

I have done a lot of research wanting to figure out what is going on, and the process of execution goes as follows
me and 3 other friends get ftb Revelations from the FTB Launcher (V. 2.6.0) and hosted the game via Logmein Hamachi. In the game for whatever reason it kicks us in our base and have no idea why. We look into our logs and found this `io.netty.util.IllegalReferenceCountException: refCnt: 0` for every player, which after researching that error and many pages later found this one [Mojand MC-87041](https://bugs.mojang.com/browse/MC-87041). To summarize the error, it basically stated that there was too many tick updates too fast. I had no idea what could've been causing it, but when I removed the ender tank I placed just recently, it resolved the issue. (which the same process for the ender chest/pouch was resolved by removing) The only thing I used it for was lava from the nether using the pump from Ranged Pumps and chunk loaders from Railcraft.

Another interesting thing was that anytime anyone interacted with an ender chest/ ender pouch/ or ender tank. It would kick everyone else but the person that hosts it.

**Comment by covers1624** [comment]
Please test with newer versions of EnderStorage AND CodeChickenLib.
